spring:
  application:
    name: apiGateWay
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: ${POST_SERVICE_URI:lb://POST-SERVICE}
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: JwtAuthenticationFilter

            - id: connection-service
              uri: ${CONNECTION_SERVICE_URI:lb://CONNECTION-SERVICE}
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
                - name: JwtAuthenticationFilter

            - id: uploader-service
              uri: ${UPLOADER_SERVICE_URI:lb://UPLOADER-SERVICE}
              predicates:
                - Path=/api/v1/uploader/**
              filters:
                - StripPrefix=2
                - name: JwtAuthenticationFilter

            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URI:lb://NOTIFICATION-SERVICE}
              predicates:
                - Path=/api/v1/notification/**
              filters:
                - StripPrefix=2
                - name: JwtAuthenticationFilter



eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka

jwt:
  secret:  ajnfiofnvinwirsigniowornkmikmvoknisngengogiieriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii